import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

function getBuildId(): string {
  // In production, read the BUILD_ID generated by Next.js at build time
  try {
    const buildIdPath = path.join(process.cwd(), '.next', 'BUILD_ID');
    return fs.readFileSync(buildIdPath, 'utf-8').trim();
  } catch {
    // Fallback: should not happen in a properly built app
    return 'unknown';
  }
}

const BUILD_ID = getBuildId();

export async function GET() {
  return NextResponse.json(
    { buildId: BUILD_ID },
    {
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate',
      },
    }
  );
}
