import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

interface BuildInfo {
  buildId: string;
  version: string;
  env: string;
  deployedAt: string | null;
}

function getBuildId(): string {
  // In production, read the BUILD_ID generated by Next.js at build time.
  try {
    const buildIdPath = path.join(process.cwd(), '.next', 'BUILD_ID');
    return fs.readFileSync(buildIdPath, 'utf-8').trim();
  } catch {
    // Fallback (dev mode, or pre-build): probar git hash si esta disponible.
    try {
      const gitHeadPath = path.join(process.cwd(), '.git', 'HEAD');
      const head = fs.readFileSync(gitHeadPath, 'utf-8').trim();
      const match = /^ref:\s+(.+)$/.exec(head);
      if (match) {
        const refPath = path.join(process.cwd(), '.git', match[1]);
        return fs.readFileSync(refPath, 'utf-8').trim().slice(0, 7);
      }
      return head.slice(0, 7);
    } catch {
      return 'dev';
    }
  }
}

// Fecha del commit deployado — inlineada en build time por next.config.ts
// (BUILD_COMMIT_DATE, via `git log -1 --format=%cI`, con git disponible en
// la maquina de build). Probamos antes con el mtime de .next/BUILD_ID en
// runtime y en Vercel devolvia una fecha fija sin relacion con el deploy
// real (la capa de cache/build reproducible lo pisa) — por eso se saca del
// commit en vez del filesystem.
function getBuildTime(): string | null {
  return process.env.BUILD_COMMIT_DATE ?? null;
}

function getPackageVersion(): string {
  try {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf-8')
    ) as { version?: string };
    return pkg.version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

const INFO: BuildInfo = {
  buildId: getBuildId(),
  version: getPackageVersion(),
  env: process.env.NODE_ENV ?? 'production',
  deployedAt: getBuildTime(),
};

export async function GET() {
  return NextResponse.json(INFO, {
    headers: {
      'Cache-Control': 'public, s-maxage=600, stale-while-revalidate=1200',
    },
  });
}
