import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

interface BuildInfo {
  buildId: string;
  version: string;
  env: string;
}

function getBuildId(): string {
  // In production, read the BUILD_ID generated by Next.js at build time.
  try {
    const buildIdPath = path.join(process.cwd(), '.next', 'BUILD_ID');
    return fs.readFileSync(buildIdPath, 'utf-8').trim();
  } catch {
    // Fallback (dev mode, or pre-build): probar git hash si esta disponible.
    try {
      const gitHeadPath = path.join(process.cwd(), '.git', 'HEAD');
      const head = fs.readFileSync(gitHeadPath, 'utf-8').trim();
      const match = /^ref:\s+(.+)$/.exec(head);
      if (match) {
        const refPath = path.join(process.cwd(), '.git', match[1]);
        return fs.readFileSync(refPath, 'utf-8').trim().slice(0, 7);
      }
      return head.slice(0, 7);
    } catch {
      return 'dev';
    }
  }
}

function getPackageVersion(): string {
  try {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf-8')
    ) as { version?: string };
    return pkg.version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

const INFO: BuildInfo = {
  buildId: getBuildId(),
  version: getPackageVersion(),
  env: process.env.NODE_ENV ?? 'production',
};

export async function GET() {
  return NextResponse.json(INFO, {
    headers: {
      'Cache-Control': 'no-store, no-cache, must-revalidate',
    },
  });
}
